#!/bin/bash
# Skill management: list, create, disable (archive), enable, delete.
# Only skills/ is edited; prompts/ and workflows/ are regenerated by release.sh.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/skills"
ARCHIVE_DIR="$REPO_ROOT/archive/skills"

GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

usage() {
    cat <<USAGE
Usage: $0 <command> [name] [--force]

  list              List active and archived skills
  create <name>     Scaffold skills/<name>/SKILL.md
  disable <name>    Move skill to archive/skills/ (git-tracked)
  enable <name>     Restore skill from archive
  delete <name>     Permanently delete (asks unless --force)

After any change: ./release.sh --all
USAGE
}

names_in() { for d in "$1"/*/; do [ -f "$d/SKILL.md" ] && basename "$d"; done 2>/dev/null; }

cmd_list() {
    echo -e "${BLUE}=== Active ===${NC}";   for s in $(names_in "$SKILLS_DIR");  do echo -e "  ${GREEN}●${NC} $s"; done
    echo -e "${BLUE}=== Archived ===${NC}"; for s in $(names_in "$ARCHIVE_DIR"); do echo -e "  ${YELLOW}○${NC} $s"; done
}

cmd_create() {
    local name="$1"
    [ -n "$name" ] || { echo -e "${RED}Error: name required${NC}"; exit 1; }
    [[ "$name" =~ ^[a-z0-9-]+$ ]] || { echo -e "${RED}Error: lowercase letters, digits, hyphens only${NC}"; exit 1; }
    [ -d "$SKILLS_DIR/$name" ] && { echo -e "${RED}Error: '$name' already exists${NC}"; exit 1; }
    [ -d "$ARCHIVE_DIR/$name" ] && { echo -e "${RED}Error: '$name' is archived; use enable${NC}"; exit 1; }
    mkdir -p "$SKILLS_DIR/$name"
    cat > "$SKILLS_DIR/$name/SKILL.md" <<SKILL
---
name: $name
description: TODO — what it does. Use when the user asks for ... or mentions "...".
---

# $name

First principle: TODO — the one idea this skill exists to protect.

- TODO: step
SKILL
    echo -e "${GREEN}✓ Created $SKILLS_DIR/$name/SKILL.md${NC}"
}

cmd_disable() {
    local name="$1"
    [ -d "$SKILLS_DIR/$name" ] || { echo -e "${RED}Error: '$name' not active${NC}"; exit 1; }
    mkdir -p "$ARCHIVE_DIR"; mv "$SKILLS_DIR/$name" "$ARCHIVE_DIR/$name"
    echo -e "${GREEN}✓ Archived '$name'${NC}"
}

cmd_enable() {
    local name="$1"
    [ -d "$ARCHIVE_DIR/$name" ] || { echo -e "${RED}Error: '$name' not in archive${NC}"; exit 1; }
    mv "$ARCHIVE_DIR/$name" "$SKILLS_DIR/$name"
    echo -e "${GREEN}✓ Restored '$name'${NC}"
}

cmd_delete() {
    local name="$1" force="$2" path=""
    if   [ -d "$SKILLS_DIR/$name" ];  then path="$SKILLS_DIR/$name"
    elif [ -d "$ARCHIVE_DIR/$name" ]; then path="$ARCHIVE_DIR/$name"
    else echo -e "${RED}Error: '$name' not found${NC}"; exit 1; fi
    if [ "$force" != "--force" ]; then
        read -p "Permanently delete $path? (y/N) " -n 1 -r; echo
        [[ $REPLY =~ ^[Yy]$ ]] || { echo "Cancelled."; exit 0; }
    fi
    rm -rf "$path"; echo -e "${GREEN}✓ Deleted '$name'${NC}"
}

[ $# -gt 0 ] || { usage; exit 1; }
cmd="$1"; shift
case $cmd in
    list)    cmd_list ;;
    create)  cmd_create "$1" ;;
    disable) cmd_disable "$1" ;;
    enable)  cmd_enable "$1" ;;
    delete)  cmd_delete "$1" "$2" ;;
    help|--help|-h) usage ;;
    *) echo -e "${RED}Unknown command '$cmd'${NC}"; usage; exit 1 ;;
esac
